version: '3'
services:
    flutter-env:
        image: flutter-ns
        build:
            context: .
        volumes:
            # Update this to wherever you want VS Code to mount the folder of your
            - type: bind
              source: ../
              target: /home/developer/workspace
              consistency: delegated
            - type: bind
              source: /dev/bus/usb
              target: /dev/bus/usb
        network_mode: host
        privileged: true
        tty: true